# Generated by Django 4.1.5 on 2023-07-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_remove_appointment_accepted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='accepted_date',
            field=models.DateField(null=True),
        ),
    ]
